### PR TITLE
Blind control

### PR DESCRIPTION
**Pull request by sthorsen**
Hi, This is not really a pull request. I just waned to give something back as I have been using your project to make a tradfri-go-blind-server to manage my Ikea smart blinds.

I don't know if you can use this, and maybe implement blind control in your project :)

I have also added docker components to build it and run the server as a docker container :)

Here are an export from all my devices, maybe it is useful for you as well:

```
[{'15015': [{'5536': 0.0, '9003': 0}],
  '3': {'0': 'IKEA of Sweden',
        '1': 'FYRTUR block-out roller blind',
        '2': '',
        '3': '2.2.009',
        '6': 3,
        '9': 62},
  '5750': 7,
  '9001': 'Right',
  '9002': 1567889303,
  '9003': 65542,
  '9019': 0,
  '9020': 1577379042,
  '9054': 0},
 {'15015': [{'5536': 50.0, '9003': 0}],
  '3': {'0': 'IKEA of Sweden',
        '1': 'FYRTUR block-out roller blind',
        '2': '',
        '3': '2.2.009',
        '6': 3,
        '9': 0},
  '5750': 7,
  '9001': 'Left Blind',
  '9002': 1567863795,
  '9003': 65538,
  '9019': 0,
  '9020': 1580082181,
  '9054': 0},
 {'15009': [{'9003': 0}],
  '3': {'0': '\x02KE',
        '1': 'TRADFRI open/close remote',
        '2': '',
        '3': '2.2.010',
        '6': 3,
        '9': 100},
  '5750': 0,
  '9001': 'TRADFRI open/close remote 2',
  '9002': 1567867466,
  '9003': 65540,
  '9019': 1,
  '9020': 1581279506,
  '9054': 0},
 {'15014': [{'9003': 0}],
  '3': {'0': 'IKEA of Sweden',
        '1': 'TRADFRI signal repeater',
        '2': '',
        '3': '2.2.005',
        '6': 1},
  '5750': 6,
  '9001': 'TRADFRI signal repeater',
  '9002': 1567863721,
  '9003': 65537,
  '9019': 1,
  '9020': 1581259898,
  '9054': 0},
 {'15015': [{'5536': 42.0, '9003': 0}],
  '3': {'0': 'IKEA of Sweden',
        '1': 'FYRTUR block-out roller blind',
        '2': '',
        '3': '2.2.009',
        '6': 3,
        '9': 86},
  '5750': 7,
  '9001': 'Right Blind',
  '9002': 1567863962,
  '9003': 65539,
  '9019': 1,
  '9020': 1581213029,
  '9054': 0},
 {'15009': [{'9003': 0}],
  '3': {'0': '\x02KE',
        '1': 'TRADFRI open/close remote',
        '2': '',
        '3': '2.2.010',
        '6': 3,
        '9': 100},
  '5750': 0,
  '9001': 'TRADFRI open/close remote',
  '9002': 1567863692,
  '9003': 65536,
  '9019': 1,
  '9020': 1581209407,
  '9054': 0},
 {'15015': [{'5536': 20.0, '9003': 0}],
  '3': {'0': 'IKEA of Sweden',
        '1': 'FYRTUR block-out roller blind',
        '2': '',
        '3': '2.2.009',
        '6': 3,
        '9': 90},
  '5750': 7,
  '9001': 'left',
  '9002': 1567868063,
  '9003': 65541,
  '9019': 1,
  '9020': 1581271368,
  '9054': 0}]
```

### CODE REVIEW

**Comment by eriklupander** [comment]
Hi!

really nice work with blind control!

I'll definitely take a look at picking out the blind control parts of your PR and see if I can merge them into the codebase. I don't have any blinds myself, guess this is as good a reason as any to get a few to experiment with :)

I'll leave the PR open for now. Looking at the diff I see your point about it not really being a PR since you've removed a lot of the lights/outlet/etc. stuff.

Thanks!

**Comment by sthorsen** [comment]
Hi, no problem

I know, it is not really a PR. I only have blinds, no lights.
If you need any help or information about the blinds, please don't hesitate to reach out :)

Have fun, looking forward for the next version. :)

**Comment by eriklupander** [comment]
Hi again,

I've extracted parts of your blinds support and pushed into the master branch. I did however make a slight API change:

The REST endpoint for setting the positioning is PUT only and will only accept the positioning in the PUT JSON body. I.e: `/api/device/65552/position/{pos}` is not included, one must use `/api/device/65552/position` with your JSON body. This adheres better with the rest (pun intended!) of the endpoints.

Would be cool if you could test and see if the latest build works for positioning your blinds. Thanks!

**Comment by sthorsen** [comment]
Hi

Awesome work. I will test it in the weekend :)

**Comment by eriklupander** [comment]
Since I manually merged the blinds code into master I'm closing this PR. Thanks!

**Pull request closed without merging**
